### ISSUE TITLE
Does persName role type have a controlled vocabulary?

### ISSUE THREAD

**Issue by wsalesky** [srophe/tei-editor#7]

**Comment by nathangibson** [comment]
Not yet, that I'm aware of. Do you have an example? I'm not aware of any use so far of persName/@role, but do you mean author/@role and editor/@role?

@davidamichelson and I need to discuss making a controlled vocabulary for role on author | editor, but for now I have been using the following:
- attributed
- disputed
- pseudo
- redactor
- scribe
- translator

Also, in the teiHeader (titleStmt and seriesStmt), we use 
- editor/@role='general'
- editor/@role='creator' in header

In the mss module, I see that person/@role='scribe' is currently being used. @davidamichelson Will this stay the same?

**Comment by wsalesky** [comment]
Yes, sorry I mean on the child elements such as roleName, foreName, addName.

**Comment by nathangibson** [comment]
Oh, yes, that's a different matter. Not officially a controlled vocabulary, but it's pretty stable. Let me take a look.

**Comment by nathangibson** [comment]
We should create a canonical list, but current usage is:
- roleName types
  - office
  - saint
- addName types
  - family
  - untagged-title

There were a couple mistaken type attributes on addName ('role' and 'title'), but I've corrected these (haven't merged yet).

Is this what you need?

**Comment by wsalesky** [comment]
Yes, that is great.
Thank you.
-Winona
